#version: "3.9"

services:

  nginx:
    image: nginx
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    depends_on:
      - php-fpm
    ports:
      - "8050:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
      - ./volumes:/var/www/html/volumes
    networks:
      - app_network

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./.env:/var/www/.env:ro
      - db:/var/www/db
      - jobs:/var/www/jobs
      - ./volumes:/var/www/html/volumes
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

  # https://github.com/wayubi/video-dedup/
  video-dedup:
    build:
      context: ./video-dedup
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./video-dedup/src:/opt/video-dedup/src
      - video-dedup-cache:/opt/video-dedup/.dedup_cache
      - ./volumes:/videos
    working_dir: /opt/video-dedup
    networks:
      - app_network
    command: tail -f /dev/null

networks:
  app_network:

volumes:
  db:
  jobs:
  video-dedup-cache:
